# Generated by Django 6.1 on 2026-08-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habito',
            name='frecuencia',
            field=models.CharField(choices=[('todos', 'Todos los días'), ('dias', 'Días específicos')], default='todos', max_length=10),
        ),
        migrations.AddField(
            model_name='habito',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habito',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habito',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habito',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habito',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habito',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
    ]
